"""initial_schema_v4

Revision ID: 782b773f85b0
Revises: 
Create Date: 2026-03-17 18:22:02.179474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782b773f85b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('growing_season', sa.String(length=255), nullable=True),
    sa.Column('soil_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_crop_name'), 'crops', ['crop_name'], unique=True)
    op.create_table('fertilizer_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fertilizer_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('plant_name', sa.String(length=100), nullable=True),
    sa.Column('plant_type', sa.String(length=50), nullable=True),
    sa.Column('issue', sa.String(length=255), nullable=True),
    sa.Column('recommended_quantity', sa.String(length=100), nullable=True),
    sa.Column('application_stage', sa.String(length=255), nullable=True),
    sa.Column('application_method', sa.Text(), nullable=True),
    sa.Column('precaution', sa.Text(), nullable=True),
    sa.Column('main_nutrients', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_warning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fertilizer_knowledge_fertilizer_name'), 'fertilizer_knowledge', ['fertilizer_name'], unique=True)
    op.create_index(op.f('ix_fertilizer_knowledge_plant_name'), 'fertilizer_knowledge', ['plant_name'], unique=False)
    op.create_table('pesticide_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=True),
    sa.Column('pest_name', sa.String(length=255), nullable=True),
    sa.Column('organic_pesticide', sa.String(length=255), nullable=True),
    sa.Column('chemical_pesticide', sa.String(length=255), nullable=True),
    sa.Column('application_method', sa.Text(), nullable=True),
    sa.Column('safety_warning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesticide_knowledge_crop_name'), 'pesticide_knowledge', ['crop_name'], unique=False)
    op.create_table('soil_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deficiency_name', sa.String(length=255), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('recommended_fertilizer', sa.Text(), nullable=True),
    sa.Column('organic_solution', sa.Text(), nullable=True),
    sa.Column('chemical_solution', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('reference_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_issues_deficiency_name'), 'soil_issues', ['deficiency_name'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_category', sa.String(length=100), nullable=True),
    sa.Column('recommended_crop', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_tool_name'), 'tools', ['tool_name'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_language'), 'translations', ['language'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopkeeper_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_crop', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_shopkeeper_id'), 'advisories', ['shopkeeper_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('crop_fertilizer_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('fertilizer_id', sa.UUID(), nullable=False),
    sa.Column('recommended_quantity', sa.String(length=100), nullable=True),
    sa.Column('application_stage', sa.String(length=255), nullable=True),
    sa.Column('application_method', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizer_knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_images_user_id'), 'crop_images', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopkeeper_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity_available', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_shopkeeper_id'), 'products', ['shopkeeper_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reminder_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_farmer_id'), 'reminders', ['farmer_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_used', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_reminders_farmer_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_products_shopkeeper_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_crop_images_user_id'), table_name='crop_images')
    op.drop_table('crop_images')
    op.drop_table('crop_fertilizer_mapping')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_advisories_shopkeeper_id'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_translations_language'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_tools_tool_name'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_soil_issues_deficiency_name'), table_name='soil_issues')
    op.drop_table('soil_issues')
    op.drop_index(op.f('ix_pesticide_knowledge_crop_name'), table_name='pesticide_knowledge')
    op.drop_table('pesticide_knowledge')
    op.drop_index(op.f('ix_fertilizer_knowledge_plant_name'), table_name='fertilizer_knowledge')
    op.drop_index(op.f('ix_fertilizer_knowledge_fertilizer_name'), table_name='fertilizer_knowledge')
    op.drop_table('fertilizer_knowledge')
    op.drop_index(op.f('ix_crops_crop_name'), table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
